
# This file is automatically generated, you probably don't want to edit this

aipwOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aipwOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            treatment = NULL,
            outcome = NULL,
            treatmentPositive = "",
            outcomePositive = "",
            outcomeType = "binary",
            outcomeCovs = NULL,
            propensityCovs = NULL,
            cluster = NULL,
            absenceVars = NULL,
            missingMethod = "fail",
            imputations = 20,
            randomSeed = 24680,
            outcomeSpecification = "pooled",
            outcomeMethod = "auto",
            propensityMethod = "auto",
            minPS = 0.01,
            maxPS = 0.99,
            bootstrapSamples = 0,
            confidenceLevel = 95,
            plotMeasure = "difference",
            sensitivityGrid = TRUE,
            showOverlapPlot = TRUE,
            showBalancePlot = TRUE,
            showEffectPlot = TRUE,
            showSyntax = TRUE, ...) {

            super$initialize(
                package="trialemulationj",
                name="aipw",
                requiresData=TRUE,
                ...)

            private$..treatment <- jmvcore::OptionVariable$new(
                "treatment",
                treatment)
            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome)
            private$..treatmentPositive <- jmvcore::OptionString$new(
                "treatmentPositive",
                treatmentPositive,
                default="")
            private$..outcomePositive <- jmvcore::OptionString$new(
                "outcomePositive",
                outcomePositive,
                default="")
            private$..outcomeType <- jmvcore::OptionList$new(
                "outcomeType",
                outcomeType,
                options=list(
                    "binary",
                    "continuous"),
                default="binary")
            private$..outcomeCovs <- jmvcore::OptionVariables$new(
                "outcomeCovs",
                outcomeCovs,
                default=NULL)
            private$..propensityCovs <- jmvcore::OptionVariables$new(
                "propensityCovs",
                propensityCovs,
                default=NULL)
            private$..cluster <- jmvcore::OptionVariable$new(
                "cluster",
                cluster,
                default=NULL)
            private$..absenceVars <- jmvcore::OptionVariables$new(
                "absenceVars",
                absenceVars,
                default=NULL)
            private$..missingMethod <- jmvcore::OptionList$new(
                "missingMethod",
                missingMethod,
                options=list(
                    "fail",
                    "completeCases",
                    "hotDeckMI"),
                default="fail")
            private$..imputations <- jmvcore::OptionInteger$new(
                "imputations",
                imputations,
                min=2,
                max=100,
                default=20)
            private$..randomSeed <- jmvcore::OptionInteger$new(
                "randomSeed",
                randomSeed,
                min=1,
                max=2147483646,
                default=24680)
            private$..outcomeSpecification <- jmvcore::OptionList$new(
                "outcomeSpecification",
                outcomeSpecification,
                options=list(
                    "pooled",
                    "armSpecific"),
                default="pooled")
            private$..outcomeMethod <- jmvcore::OptionList$new(
                "outcomeMethod",
                outcomeMethod,
                options=list(
                    "auto",
                    "maximumLikelihood",
                    "firth"),
                default="auto")
            private$..propensityMethod <- jmvcore::OptionList$new(
                "propensityMethod",
                propensityMethod,
                options=list(
                    "auto",
                    "maximumLikelihood",
                    "firth"),
                default="auto")
            private$..minPS <- jmvcore::OptionNumber$new(
                "minPS",
                minPS,
                min=0.0001,
                max=0.49,
                default=0.01)
            private$..maxPS <- jmvcore::OptionNumber$new(
                "maxPS",
                maxPS,
                min=0.51,
                max=0.9999,
                default=0.99)
            private$..bootstrapSamples <- jmvcore::OptionInteger$new(
                "bootstrapSamples",
                bootstrapSamples,
                min=0,
                max=10000,
                default=0)
            private$..confidenceLevel <- jmvcore::OptionNumber$new(
                "confidenceLevel",
                confidenceLevel,
                min=80,
                max=99.9,
                default=95)
            private$..plotMeasure <- jmvcore::OptionList$new(
                "plotMeasure",
                plotMeasure,
                options=list(
                    "difference",
                    "riskRatio",
                    "oddsRatio"),
                default="difference")
            private$..sensitivityGrid <- jmvcore::OptionBool$new(
                "sensitivityGrid",
                sensitivityGrid,
                default=TRUE)
            private$..showOverlapPlot <- jmvcore::OptionBool$new(
                "showOverlapPlot",
                showOverlapPlot,
                default=TRUE)
            private$..showBalancePlot <- jmvcore::OptionBool$new(
                "showBalancePlot",
                showBalancePlot,
                default=TRUE)
            private$..showEffectPlot <- jmvcore::OptionBool$new(
                "showEffectPlot",
                showEffectPlot,
                default=TRUE)
            private$..showSyntax <- jmvcore::OptionBool$new(
                "showSyntax",
                showSyntax,
                default=TRUE)

            self$.addOption(private$..treatment)
            self$.addOption(private$..outcome)
            self$.addOption(private$..treatmentPositive)
            self$.addOption(private$..outcomePositive)
            self$.addOption(private$..outcomeType)
            self$.addOption(private$..outcomeCovs)
            self$.addOption(private$..propensityCovs)
            self$.addOption(private$..cluster)
            self$.addOption(private$..absenceVars)
            self$.addOption(private$..missingMethod)
            self$.addOption(private$..imputations)
            self$.addOption(private$..randomSeed)
            self$.addOption(private$..outcomeSpecification)
            self$.addOption(private$..outcomeMethod)
            self$.addOption(private$..propensityMethod)
            self$.addOption(private$..minPS)
            self$.addOption(private$..maxPS)
            self$.addOption(private$..bootstrapSamples)
            self$.addOption(private$..confidenceLevel)
            self$.addOption(private$..plotMeasure)
            self$.addOption(private$..sensitivityGrid)
            self$.addOption(private$..showOverlapPlot)
            self$.addOption(private$..showBalancePlot)
            self$.addOption(private$..showEffectPlot)
            self$.addOption(private$..showSyntax)
        }),
    active = list(
        treatment = function() private$..treatment$value,
        outcome = function() private$..outcome$value,
        treatmentPositive = function() private$..treatmentPositive$value,
        outcomePositive = function() private$..outcomePositive$value,
        outcomeType = function() private$..outcomeType$value,
        outcomeCovs = function() private$..outcomeCovs$value,
        propensityCovs = function() private$..propensityCovs$value,
        cluster = function() private$..cluster$value,
        absenceVars = function() private$..absenceVars$value,
        missingMethod = function() private$..missingMethod$value,
        imputations = function() private$..imputations$value,
        randomSeed = function() private$..randomSeed$value,
        outcomeSpecification = function() private$..outcomeSpecification$value,
        outcomeMethod = function() private$..outcomeMethod$value,
        propensityMethod = function() private$..propensityMethod$value,
        minPS = function() private$..minPS$value,
        maxPS = function() private$..maxPS$value,
        bootstrapSamples = function() private$..bootstrapSamples$value,
        confidenceLevel = function() private$..confidenceLevel$value,
        plotMeasure = function() private$..plotMeasure$value,
        sensitivityGrid = function() private$..sensitivityGrid$value,
        showOverlapPlot = function() private$..showOverlapPlot$value,
        showBalancePlot = function() private$..showBalancePlot$value,
        showEffectPlot = function() private$..showEffectPlot$value,
        showSyntax = function() private$..showSyntax$value),
    private = list(
        ..treatment = NA,
        ..outcome = NA,
        ..treatmentPositive = NA,
        ..outcomePositive = NA,
        ..outcomeType = NA,
        ..outcomeCovs = NA,
        ..propensityCovs = NA,
        ..cluster = NA,
        ..absenceVars = NA,
        ..missingMethod = NA,
        ..imputations = NA,
        ..randomSeed = NA,
        ..outcomeSpecification = NA,
        ..outcomeMethod = NA,
        ..propensityMethod = NA,
        ..minPS = NA,
        ..maxPS = NA,
        ..bootstrapSamples = NA,
        ..confidenceLevel = NA,
        ..plotMeasure = NA,
        ..sensitivityGrid = NA,
        ..showOverlapPlot = NA,
        ..showBalancePlot = NA,
        ..showEffectPlot = NA,
        ..showSyntax = NA)
)

aipwResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aipwResults",
    inherit = jmvcore::Group,
    active = list(
        summary = function() private$.items[["summary"]],
        effects = function() private$.items[["effects"]],
        propensity = function() private$.items[["propensity"]],
        balance = function() private$.items[["balance"]],
        missingAudit = function() private$.items[["missingAudit"]],
        sensitivity = function() private$.items[["sensitivity"]],
        overlapPlot = function() private$.items[["overlapPlot"]],
        balancePlot = function() private$.items[["balancePlot"]],
        effectPlot = function() private$.items[["effectPlot"]],
        notes = function() private$.items[["notes"]],
        syntax = function() private$.items[["syntax"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="AIPW and IPTW for Point Outcomes")
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Analysis Summary",
                rows=14,
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effects",
                title="Marginal Treatment Effects",
                columns=list(
                    list(
                        `name`="method", 
                        `title`="Method", 
                        `type`="text"),
                    list(
                        `name`="estimand", 
                        `title`="Estimand", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="seScale", 
                        `title`="SE scale", 
                        `type`="text"),
                    list(
                        `name`="lower", 
                        `title`="Lower CI", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper CI", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="bootstrapSuccess", 
                        `title`="Successful bootstraps", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="propensity",
                title="Propensity and Weight Diagnostics",
                columns=list(
                    list(
                        `name`="group", 
                        `title`="Treatment group", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="psMin", 
                        `title`="PS min", 
                        `type`="number"),
                    list(
                        `name`="psMedian", 
                        `title`="PS median", 
                        `type`="number"),
                    list(
                        `name`="psMax", 
                        `title`="PS max", 
                        `type`="number"),
                    list(
                        `name`="weightMean", 
                        `title`="IPW mean", 
                        `type`="number"),
                    list(
                        `name`="weightMax", 
                        `title`="IPW max", 
                        `type`="number"),
                    list(
                        `name`="ess", 
                        `title`="Effective sample size", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="balance",
                title="Covariate Balance",
                columns=list(
                    list(
                        `name`="covariate", 
                        `title`="Covariate / level", 
                        `type`="text"),
                    list(
                        `name`="unweighted", 
                        `title`="Unweighted SMD", 
                        `type`="number"),
                    list(
                        `name`="weighted", 
                        `title`="IPTW-weighted SMD", 
                        `type`="number"),
                    list(
                        `name`="acceptable", 
                        `title`="|SMD| < 0.10", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="missingAudit",
                title="Missing-Value and Recoding Audit",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="recoded", 
                        `title`="Values recoded", 
                        `type`="integer"),
                    list(
                        `name`="rule", 
                        `title`="Rule", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="sensitivity",
                title="Propensity Truncation Sensitivity",
                visible="(sensitivityGrid)",
                columns=list(
                    list(
                        `name`="limits", 
                        `title`="Propensity limits", 
                        `type`="text"),
                    list(
                        `name`="method", 
                        `title`="Method", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Difference", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower CI", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper CI", 
                        `type`="number"),
                    list(
                        `name`="truncated", 
                        `title`="Truncated N", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="overlapPlot",
                title="Propensity-Score Overlap",
                visible="(showOverlapPlot)",
                width=650,
                height=420,
                renderFun=".overlapPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="balancePlot",
                title="Covariate Balance Before and After Weighting",
                visible="(showBalancePlot)",
                width=760,
                height=500,
                renderFun=".balancePlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="effectPlot",
                title="AIPW and IPTW Effect Estimates",
                visible="(showEffectPlot)",
                width=700,
                height=360,
                renderFun=".effectPlot"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="notes",
                title="Interpretation and Diagnostics"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="syntax",
                title="Reproducible R Syntax",
                visible="(showSyntax)"))}))

aipwBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "aipwBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "trialemulationj",
                name = "aipw",
                version = c(1,1,1),
                options = options,
                results = aipwResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' AIPW and IPTW for Point Outcomes
#'
#' Estimates marginal treatment effects using augmented inverse probability
#' weighting (AIPW) and Hajek inverse probability weighting (IPTW). Supports
#' clustered influence-function inference, whole-cluster bootstrap confidence
#' intervals, Firth bias-reduced logistic models, explicit missing-value
#' policies, and publication-ready diagnostic plots.
#' 
#' @param data .
#' @param treatment .
#' @param outcome .
#' @param treatmentPositive .
#' @param outcomePositive .
#' @param outcomeType .
#' @param outcomeCovs .
#' @param propensityCovs .
#' @param cluster .
#' @param absenceVars .
#' @param missingMethod .
#' @param imputations .
#' @param randomSeed .
#' @param outcomeSpecification .
#' @param outcomeMethod .
#' @param propensityMethod .
#' @param minPS .
#' @param maxPS .
#' @param bootstrapSamples .
#' @param confidenceLevel .
#' @param plotMeasure .
#' @param sensitivityGrid .
#' @param showOverlapPlot .
#' @param showBalancePlot .
#' @param showEffectPlot .
#' @param showSyntax .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effects} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$propensity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$balance} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$missingAudit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$sensitivity} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$overlapPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$balancePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$effectPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$syntax} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
aipw <- function(
    data,
    treatment,
    outcome,
    treatmentPositive = "",
    outcomePositive = "",
    outcomeType = "binary",
    outcomeCovs = NULL,
    propensityCovs = NULL,
    cluster = NULL,
    absenceVars = NULL,
    missingMethod = "fail",
    imputations = 20,
    randomSeed = 24680,
    outcomeSpecification = "pooled",
    outcomeMethod = "auto",
    propensityMethod = "auto",
    minPS = 0.01,
    maxPS = 0.99,
    bootstrapSamples = 0,
    confidenceLevel = 95,
    plotMeasure = "difference",
    sensitivityGrid = TRUE,
    showOverlapPlot = TRUE,
    showBalancePlot = TRUE,
    showEffectPlot = TRUE,
    showSyntax = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("aipw requires jmvcore to be installed (restart may be required)")

    if ( ! missing(treatment)) treatment <- jmvcore::resolveQuo(jmvcore::enquo(treatment))
    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(outcomeCovs)) outcomeCovs <- jmvcore::resolveQuo(jmvcore::enquo(outcomeCovs))
    if ( ! missing(propensityCovs)) propensityCovs <- jmvcore::resolveQuo(jmvcore::enquo(propensityCovs))
    if ( ! missing(cluster)) cluster <- jmvcore::resolveQuo(jmvcore::enquo(cluster))
    if ( ! missing(absenceVars)) absenceVars <- jmvcore::resolveQuo(jmvcore::enquo(absenceVars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(treatment), treatment, NULL),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(outcomeCovs), outcomeCovs, NULL),
            `if`( ! missing(propensityCovs), propensityCovs, NULL),
            `if`( ! missing(cluster), cluster, NULL),
            `if`( ! missing(absenceVars), absenceVars, NULL))


    options <- aipwOptions$new(
        treatment = treatment,
        outcome = outcome,
        treatmentPositive = treatmentPositive,
        outcomePositive = outcomePositive,
        outcomeType = outcomeType,
        outcomeCovs = outcomeCovs,
        propensityCovs = propensityCovs,
        cluster = cluster,
        absenceVars = absenceVars,
        missingMethod = missingMethod,
        imputations = imputations,
        randomSeed = randomSeed,
        outcomeSpecification = outcomeSpecification,
        outcomeMethod = outcomeMethod,
        propensityMethod = propensityMethod,
        minPS = minPS,
        maxPS = maxPS,
        bootstrapSamples = bootstrapSamples,
        confidenceLevel = confidenceLevel,
        plotMeasure = plotMeasure,
        sensitivityGrid = sensitivityGrid,
        showOverlapPlot = showOverlapPlot,
        showBalancePlot = showBalancePlot,
        showEffectPlot = showEffectPlot,
        showSyntax = showSyntax)

    analysis <- aipwClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

