
# This file is automatically generated, you probably don't want to edit this

causalDAGOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "causalDAGOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            exposure = NULL,
            outcome = NULL,
            selectedAdjusters = NULL,
            dagText = "",
            effect = "total",
            maxSets = 20,
            showIndependencies = TRUE,
            showPlot = TRUE,
            showSyntax = TRUE, ...) {

            super$initialize(
                package="trialemulationj",
                name="causalDAG",
                requiresData=TRUE,
                ...)

            private$..exposure <- jmvcore::OptionVariable$new(
                "exposure",
                exposure)
            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome)
            private$..selectedAdjusters <- jmvcore::OptionVariables$new(
                "selectedAdjusters",
                selectedAdjusters,
                default=NULL)
            private$..dagText <- jmvcore::OptionString$new(
                "dagText",
                dagText,
                default="")
            private$..effect <- jmvcore::OptionList$new(
                "effect",
                effect,
                options=list(
                    "total",
                    "direct"),
                default="total")
            private$..maxSets <- jmvcore::OptionInteger$new(
                "maxSets",
                maxSets,
                min=1,
                max=100,
                default=20)
            private$..showIndependencies <- jmvcore::OptionBool$new(
                "showIndependencies",
                showIndependencies,
                default=TRUE)
            private$..showPlot <- jmvcore::OptionBool$new(
                "showPlot",
                showPlot,
                default=TRUE)
            private$..showSyntax <- jmvcore::OptionBool$new(
                "showSyntax",
                showSyntax,
                default=TRUE)

            self$.addOption(private$..exposure)
            self$.addOption(private$..outcome)
            self$.addOption(private$..selectedAdjusters)
            self$.addOption(private$..dagText)
            self$.addOption(private$..effect)
            self$.addOption(private$..maxSets)
            self$.addOption(private$..showIndependencies)
            self$.addOption(private$..showPlot)
            self$.addOption(private$..showSyntax)
        }),
    active = list(
        exposure = function() private$..exposure$value,
        outcome = function() private$..outcome$value,
        selectedAdjusters = function() private$..selectedAdjusters$value,
        dagText = function() private$..dagText$value,
        effect = function() private$..effect$value,
        maxSets = function() private$..maxSets$value,
        showIndependencies = function() private$..showIndependencies$value,
        showPlot = function() private$..showPlot$value,
        showSyntax = function() private$..showSyntax$value),
    private = list(
        ..exposure = NA,
        ..outcome = NA,
        ..selectedAdjusters = NA,
        ..dagText = NA,
        ..effect = NA,
        ..maxSets = NA,
        ..showIndependencies = NA,
        ..showPlot = NA,
        ..showSyntax = NA)
)

causalDAGResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "causalDAGResults",
    inherit = jmvcore::Group,
    active = list(
        summary = function() private$.items[["summary"]],
        adjustmentSets = function() private$.items[["adjustmentSets"]],
        selected = function() private$.items[["selected"]],
        independencies = function() private$.items[["independencies"]],
        dagPlot = function() private$.items[["dagPlot"]],
        notes = function() private$.items[["notes"]],
        syntax = function() private$.items[["syntax"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Causal DAG and Adjustment Sets")
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Graph Summary",
                rows=8,
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="adjustmentSets",
                title="Minimally Sufficient Adjustment Sets",
                columns=list(
                    list(
                        `name`="number", 
                        `title`="Set", 
                        `type`="integer"),
                    list(
                        `name`="variables", 
                        `title`="Variables", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="selected",
                title="Selected-Covariate Check",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="status", 
                        `title`="Status", 
                        `type`="text"),
                    list(
                        `name`="explanation", 
                        `title`="Explanation", 
                        `type`="text"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="independencies",
                title="Implied Conditional Independencies",
                visible="(showIndependencies)"))
            self$add(jmvcore::Image$new(
                options=options,
                name="dagPlot",
                title="Prespecified Causal DAG",
                visible="(showPlot)",
                width=760,
                height=520,
                renderFun=".dagPlot"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="notes",
                title="Interpretation and Safeguards"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="syntax",
                title="Validated DAGitty Syntax",
                visible="(showSyntax)"))}))

causalDAGBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "causalDAGBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "trialemulationj",
                name = "causalDAG",
                version = c(1,1,1),
                options = options,
                results = causalDAGResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Causal DAG and Adjustment Sets
#'
#' Validates a prespecified causal directed acyclic graph, identifies
#' minimally sufficient adjustment sets, checks a selected model set, and
#' produces a publication-ready static graph. The analysis does not learn
#' causal structure from the observed data.
#' 
#' @param data .
#' @param exposure .
#' @param outcome .
#' @param selectedAdjusters .
#' @param dagText .
#' @param effect .
#' @param maxSets .
#' @param showIndependencies .
#' @param showPlot .
#' @param showSyntax .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$adjustmentSets} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$selected} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$independencies} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$dagPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$syntax} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
causalDAG <- function(
    data,
    exposure,
    outcome,
    selectedAdjusters = NULL,
    dagText = "",
    effect = "total",
    maxSets = 20,
    showIndependencies = TRUE,
    showPlot = TRUE,
    showSyntax = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("causalDAG requires jmvcore to be installed (restart may be required)")

    if ( ! missing(exposure)) exposure <- jmvcore::resolveQuo(jmvcore::enquo(exposure))
    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(selectedAdjusters)) selectedAdjusters <- jmvcore::resolveQuo(jmvcore::enquo(selectedAdjusters))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(exposure), exposure, NULL),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(selectedAdjusters), selectedAdjusters, NULL))


    options <- causalDAGOptions$new(
        exposure = exposure,
        outcome = outcome,
        selectedAdjusters = selectedAdjusters,
        dagText = dagText,
        effect = effect,
        maxSets = maxSets,
        showIndependencies = showIndependencies,
        showPlot = showPlot,
        showSyntax = showSyntax)

    analysis <- causalDAGClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

