
# This file is automatically generated, you probably don't want to edit this

cloneCensorOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cloneCensorOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            id = NULL,
            event = NULL,
            timeToEvent = NULL,
            exposure = NULL,
            timeToExposure = NULL,
            weightCovs = NULL,
            gracePeriod = 100,
            horizon = 365,
            winsorize = TRUE,
            lowerPercentile = 1,
            upperPercentile = 99,
            winsorizeByClone = FALSE,
            bootstrapSamples = 500,
            seed = 20240219,
            showWeightPlot = TRUE,
            showSyntax = TRUE, ...) {

            super$initialize(
                package="trialemulationj",
                name="cloneCensor",
                requiresData=TRUE,
                ...)

            private$..id <- jmvcore::OptionVariable$new(
                "id",
                id)
            private$..event <- jmvcore::OptionVariable$new(
                "event",
                event)
            private$..timeToEvent <- jmvcore::OptionVariable$new(
                "timeToEvent",
                timeToEvent,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..exposure <- jmvcore::OptionVariable$new(
                "exposure",
                exposure)
            private$..timeToExposure <- jmvcore::OptionVariable$new(
                "timeToExposure",
                timeToExposure,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..weightCovs <- jmvcore::OptionVariables$new(
                "weightCovs",
                weightCovs,
                default=NULL)
            private$..gracePeriod <- jmvcore::OptionNumber$new(
                "gracePeriod",
                gracePeriod,
                min=0.000001,
                default=100)
            private$..horizon <- jmvcore::OptionNumber$new(
                "horizon",
                horizon,
                min=0.000001,
                default=365)
            private$..winsorize <- jmvcore::OptionBool$new(
                "winsorize",
                winsorize,
                default=TRUE)
            private$..lowerPercentile <- jmvcore::OptionNumber$new(
                "lowerPercentile",
                lowerPercentile,
                min=0,
                max=49,
                default=1)
            private$..upperPercentile <- jmvcore::OptionNumber$new(
                "upperPercentile",
                upperPercentile,
                min=51,
                max=100,
                default=99)
            private$..winsorizeByClone <- jmvcore::OptionBool$new(
                "winsorizeByClone",
                winsorizeByClone,
                default=FALSE)
            private$..bootstrapSamples <- jmvcore::OptionInteger$new(
                "bootstrapSamples",
                bootstrapSamples,
                min=20,
                max=5000,
                default=500)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                min=1,
                default=20240219)
            private$..showWeightPlot <- jmvcore::OptionBool$new(
                "showWeightPlot",
                showWeightPlot,
                default=TRUE)
            private$..showSyntax <- jmvcore::OptionBool$new(
                "showSyntax",
                showSyntax,
                default=TRUE)

            self$.addOption(private$..id)
            self$.addOption(private$..event)
            self$.addOption(private$..timeToEvent)
            self$.addOption(private$..exposure)
            self$.addOption(private$..timeToExposure)
            self$.addOption(private$..weightCovs)
            self$.addOption(private$..gracePeriod)
            self$.addOption(private$..horizon)
            self$.addOption(private$..winsorize)
            self$.addOption(private$..lowerPercentile)
            self$.addOption(private$..upperPercentile)
            self$.addOption(private$..winsorizeByClone)
            self$.addOption(private$..bootstrapSamples)
            self$.addOption(private$..seed)
            self$.addOption(private$..showWeightPlot)
            self$.addOption(private$..showSyntax)
        }),
    active = list(
        id = function() private$..id$value,
        event = function() private$..event$value,
        timeToEvent = function() private$..timeToEvent$value,
        exposure = function() private$..exposure$value,
        timeToExposure = function() private$..timeToExposure$value,
        weightCovs = function() private$..weightCovs$value,
        gracePeriod = function() private$..gracePeriod$value,
        horizon = function() private$..horizon$value,
        winsorize = function() private$..winsorize$value,
        lowerPercentile = function() private$..lowerPercentile$value,
        upperPercentile = function() private$..upperPercentile$value,
        winsorizeByClone = function() private$..winsorizeByClone$value,
        bootstrapSamples = function() private$..bootstrapSamples$value,
        seed = function() private$..seed$value,
        showWeightPlot = function() private$..showWeightPlot$value,
        showSyntax = function() private$..showSyntax$value),
    private = list(
        ..id = NA,
        ..event = NA,
        ..timeToEvent = NA,
        ..exposure = NA,
        ..timeToExposure = NA,
        ..weightCovs = NA,
        ..gracePeriod = NA,
        ..horizon = NA,
        ..winsorize = NA,
        ..lowerPercentile = NA,
        ..upperPercentile = NA,
        ..winsorizeByClone = NA,
        ..bootstrapSamples = NA,
        ..seed = NA,
        ..showWeightPlot = NA,
        ..showSyntax = NA)
)

cloneCensorResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cloneCensorResults",
    inherit = jmvcore::Group,
    active = list(
        summary = function() private$.items[["summary"]],
        effects = function() private$.items[["effects"]],
        survivalPlot = function() private$.items[["survivalPlot"]],
        weightSummary = function() private$.items[["weightSummary"]],
        weightPlot = function() private$.items[["weightPlot"]],
        notes = function() private$.items[["notes"]],
        syntax = function() private$.items[["syntax"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Clone-Censor-Weight Survival Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Analysis Summary",
                rows=10,
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effects",
                title="Clone-Censor-Weighted Effects",
                columns=list(
                    list(
                        `name`="estimand", 
                        `title`="Estimand", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="Bootstrap SE", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower 95%", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper 95%", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="survivalPlot",
                title="Weighted Survival Curves",
                width=600,
                height=420,
                renderFun=".survivalPlot",
                clearWith=list(
                    "horizon",
                    "winsorize",
                    "lowerPercentile",
                    "upperPercentile",
                    "winsorizeByClone")))
            self$add(jmvcore::Table$new(
                options=options,
                name="weightSummary",
                title="Clone-Censor Weight Diagnostics",
                columns=list(
                    list(
                        `name`="strategy", 
                        `title`="Strategy", 
                        `type`="text"),
                    list(
                        `name`="min", 
                        `title`="Min", 
                        `type`="number"),
                    list(
                        `name`="p1", 
                        `title`="P1", 
                        `type`="number"),
                    list(
                        `name`="median", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="p99", 
                        `title`="P99", 
                        `type`="number"),
                    list(
                        `name`="max", 
                        `title`="Max", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="weightPlot",
                title="Clone-Censor Weight Distribution",
                visible="(showWeightPlot)",
                width=600,
                height=380,
                renderFun=".weightPlot"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="notes",
                title="Interpretation and Diagnostics"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="syntax",
                title="Reproducible R Syntax",
                visible="(showSyntax)"))}))

cloneCensorBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "cloneCensorBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "trialemulationj",
                name = "cloneCensor",
                version = c(1,1,1),
                options = options,
                results = cloneCensorResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Clone-Censor-Weight Survival Analysis
#'
#' Emulates sustained exposure strategies by cloning each person,
#' artificially censoring clones at strategy deviation, and weighting for
#' the induced censoring. Input data must contain one row per person.
#' 
#' @param data .
#' @param id .
#' @param event .
#' @param timeToEvent .
#' @param exposure .
#' @param timeToExposure .
#' @param weightCovs .
#' @param gracePeriod .
#' @param horizon .
#' @param winsorize .
#' @param lowerPercentile .
#' @param upperPercentile .
#' @param winsorizeByClone .
#' @param bootstrapSamples .
#' @param seed .
#' @param showWeightPlot .
#' @param showSyntax .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effects} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$survivalPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$weightSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$weightPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$syntax} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
cloneCensor <- function(
    data,
    id,
    event,
    timeToEvent,
    exposure,
    timeToExposure,
    weightCovs = NULL,
    gracePeriod = 100,
    horizon = 365,
    winsorize = TRUE,
    lowerPercentile = 1,
    upperPercentile = 99,
    winsorizeByClone = FALSE,
    bootstrapSamples = 500,
    seed = 20240219,
    showWeightPlot = TRUE,
    showSyntax = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("cloneCensor requires jmvcore to be installed (restart may be required)")

    if ( ! missing(id)) id <- jmvcore::resolveQuo(jmvcore::enquo(id))
    if ( ! missing(event)) event <- jmvcore::resolveQuo(jmvcore::enquo(event))
    if ( ! missing(timeToEvent)) timeToEvent <- jmvcore::resolveQuo(jmvcore::enquo(timeToEvent))
    if ( ! missing(exposure)) exposure <- jmvcore::resolveQuo(jmvcore::enquo(exposure))
    if ( ! missing(timeToExposure)) timeToExposure <- jmvcore::resolveQuo(jmvcore::enquo(timeToExposure))
    if ( ! missing(weightCovs)) weightCovs <- jmvcore::resolveQuo(jmvcore::enquo(weightCovs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(id), id, NULL),
            `if`( ! missing(event), event, NULL),
            `if`( ! missing(timeToEvent), timeToEvent, NULL),
            `if`( ! missing(exposure), exposure, NULL),
            `if`( ! missing(timeToExposure), timeToExposure, NULL),
            `if`( ! missing(weightCovs), weightCovs, NULL))


    options <- cloneCensorOptions$new(
        id = id,
        event = event,
        timeToEvent = timeToEvent,
        exposure = exposure,
        timeToExposure = timeToExposure,
        weightCovs = weightCovs,
        gracePeriod = gracePeriod,
        horizon = horizon,
        winsorize = winsorize,
        lowerPercentile = lowerPercentile,
        upperPercentile = upperPercentile,
        winsorizeByClone = winsorizeByClone,
        bootstrapSamples = bootstrapSamples,
        seed = seed,
        showWeightPlot = showWeightPlot,
        showSyntax = showSyntax)

    analysis <- cloneCensorClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

