
# This file is automatically generated, you probably don't want to edit this

drSurvivalOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "drSurvivalOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            time = NULL,
            event = NULL,
            treatment = NULL,
            followupTime = NULL,
            outcomeCovs = NULL,
            propensityCovs = NULL,
            censorCovs = NULL,
            horizon = 365,
            psMethod = "glm",
            censorMethod = "breslow",
            minPS = 0.01,
            maxPS = 0.99,
            minCensorSurvival = 0.025,
            bootstrapSamples = 500,
            seed = 20240219,
            showBootstrapPlot = TRUE,
            showSyntax = TRUE, ...) {

            super$initialize(
                package="trialemulationj",
                name="drSurvival",
                requiresData=TRUE,
                ...)

            private$..time <- jmvcore::OptionVariable$new(
                "time",
                time,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..event <- jmvcore::OptionVariable$new(
                "event",
                event)
            private$..treatment <- jmvcore::OptionVariable$new(
                "treatment",
                treatment)
            private$..followupTime <- jmvcore::OptionVariable$new(
                "followupTime",
                followupTime,
                default=NULL,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..outcomeCovs <- jmvcore::OptionVariables$new(
                "outcomeCovs",
                outcomeCovs,
                default=NULL)
            private$..propensityCovs <- jmvcore::OptionVariables$new(
                "propensityCovs",
                propensityCovs,
                default=NULL)
            private$..censorCovs <- jmvcore::OptionVariables$new(
                "censorCovs",
                censorCovs,
                default=NULL)
            private$..horizon <- jmvcore::OptionNumber$new(
                "horizon",
                horizon,
                min=0.000001,
                default=365)
            private$..psMethod <- jmvcore::OptionList$new(
                "psMethod",
                psMethod,
                options=list(
                    "glm",
                    "lasso"),
                default="glm")
            private$..censorMethod <- jmvcore::OptionList$new(
                "censorMethod",
                censorMethod,
                options=list(
                    "breslow",
                    "aft_exp",
                    "aft_weibull",
                    "aft_lognormal",
                    "aft_loglogistic"),
                default="breslow")
            private$..minPS <- jmvcore::OptionNumber$new(
                "minPS",
                minPS,
                min=0.0001,
                max=0.49,
                default=0.01)
            private$..maxPS <- jmvcore::OptionNumber$new(
                "maxPS",
                maxPS,
                min=0.51,
                max=0.9999,
                default=0.99)
            private$..minCensorSurvival <- jmvcore::OptionNumber$new(
                "minCensorSurvival",
                minCensorSurvival,
                min=0.0001,
                max=0.49,
                default=0.025)
            private$..bootstrapSamples <- jmvcore::OptionInteger$new(
                "bootstrapSamples",
                bootstrapSamples,
                min=20,
                max=5000,
                default=500)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                min=1,
                default=20240219)
            private$..showBootstrapPlot <- jmvcore::OptionBool$new(
                "showBootstrapPlot",
                showBootstrapPlot,
                default=TRUE)
            private$..showSyntax <- jmvcore::OptionBool$new(
                "showSyntax",
                showSyntax,
                default=TRUE)

            self$.addOption(private$..time)
            self$.addOption(private$..event)
            self$.addOption(private$..treatment)
            self$.addOption(private$..followupTime)
            self$.addOption(private$..outcomeCovs)
            self$.addOption(private$..propensityCovs)
            self$.addOption(private$..censorCovs)
            self$.addOption(private$..horizon)
            self$.addOption(private$..psMethod)
            self$.addOption(private$..censorMethod)
            self$.addOption(private$..minPS)
            self$.addOption(private$..maxPS)
            self$.addOption(private$..minCensorSurvival)
            self$.addOption(private$..bootstrapSamples)
            self$.addOption(private$..seed)
            self$.addOption(private$..showBootstrapPlot)
            self$.addOption(private$..showSyntax)
        }),
    active = list(
        time = function() private$..time$value,
        event = function() private$..event$value,
        treatment = function() private$..treatment$value,
        followupTime = function() private$..followupTime$value,
        outcomeCovs = function() private$..outcomeCovs$value,
        propensityCovs = function() private$..propensityCovs$value,
        censorCovs = function() private$..censorCovs$value,
        horizon = function() private$..horizon$value,
        psMethod = function() private$..psMethod$value,
        censorMethod = function() private$..censorMethod$value,
        minPS = function() private$..minPS$value,
        maxPS = function() private$..maxPS$value,
        minCensorSurvival = function() private$..minCensorSurvival$value,
        bootstrapSamples = function() private$..bootstrapSamples$value,
        seed = function() private$..seed$value,
        showBootstrapPlot = function() private$..showBootstrapPlot$value,
        showSyntax = function() private$..showSyntax$value),
    private = list(
        ..time = NA,
        ..event = NA,
        ..treatment = NA,
        ..followupTime = NA,
        ..outcomeCovs = NA,
        ..propensityCovs = NA,
        ..censorCovs = NA,
        ..horizon = NA,
        ..psMethod = NA,
        ..censorMethod = NA,
        ..minPS = NA,
        ..maxPS = NA,
        ..minCensorSurvival = NA,
        ..bootstrapSamples = NA,
        ..seed = NA,
        ..showBootstrapPlot = NA,
        ..showSyntax = NA)
)

drSurvivalResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "drSurvivalResults",
    inherit = jmvcore::Group,
    active = list(
        summary = function() private$.items[["summary"]],
        effects = function() private$.items[["effects"]],
        bootstrapPlot = function() private$.items[["bootstrapPlot"]],
        notes = function() private$.items[["notes"]],
        syntax = function() private$.items[["syntax"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Doubly Robust Survival Effect")
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Analysis Summary",
                rows=9,
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effects",
                title="Doubly Robust Survival Effects",
                columns=list(
                    list(
                        `name`="estimand", 
                        `title`="Estimand", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="Bootstrap SE", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower 95%", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper 95%", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="bootstrapPlot",
                title="Bootstrap Treatment-Effect Distributions",
                visible="(showBootstrapPlot)",
                width=600,
                height=400,
                renderFun=".bootstrapPlot"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="notes",
                title="Interpretation and Diagnostics"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="syntax",
                title="Reproducible R Syntax",
                visible="(showSyntax)"))}))

drSurvivalBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "drSurvivalBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "trialemulationj",
                name = "drSurvival",
                version = c(1,0,0),
                options = options,
                results = drSurvivalResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Doubly Robust Survival Effect
#'
#' Estimates a doubly robust treatment effect for one-row-per-person
#' survival data. The primary estimand is the ratio of restricted mean time
#' lost under treatment versus no treatment at a specified horizon.
#' 
#' @param data .
#' @param time .
#' @param event .
#' @param treatment .
#' @param followupTime .
#' @param outcomeCovs .
#' @param propensityCovs .
#' @param censorCovs .
#' @param horizon .
#' @param psMethod .
#' @param censorMethod .
#' @param minPS .
#' @param maxPS .
#' @param minCensorSurvival .
#' @param bootstrapSamples .
#' @param seed .
#' @param showBootstrapPlot .
#' @param showSyntax .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effects} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$bootstrapPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$syntax} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
drSurvival <- function(
    data,
    time,
    event,
    treatment,
    followupTime = NULL,
    outcomeCovs = NULL,
    propensityCovs = NULL,
    censorCovs = NULL,
    horizon = 365,
    psMethod = "glm",
    censorMethod = "breslow",
    minPS = 0.01,
    maxPS = 0.99,
    minCensorSurvival = 0.025,
    bootstrapSamples = 500,
    seed = 20240219,
    showBootstrapPlot = TRUE,
    showSyntax = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("drSurvival requires jmvcore to be installed (restart may be required)")

    if ( ! missing(time)) time <- jmvcore::resolveQuo(jmvcore::enquo(time))
    if ( ! missing(event)) event <- jmvcore::resolveQuo(jmvcore::enquo(event))
    if ( ! missing(treatment)) treatment <- jmvcore::resolveQuo(jmvcore::enquo(treatment))
    if ( ! missing(followupTime)) followupTime <- jmvcore::resolveQuo(jmvcore::enquo(followupTime))
    if ( ! missing(outcomeCovs)) outcomeCovs <- jmvcore::resolveQuo(jmvcore::enquo(outcomeCovs))
    if ( ! missing(propensityCovs)) propensityCovs <- jmvcore::resolveQuo(jmvcore::enquo(propensityCovs))
    if ( ! missing(censorCovs)) censorCovs <- jmvcore::resolveQuo(jmvcore::enquo(censorCovs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(time), time, NULL),
            `if`( ! missing(event), event, NULL),
            `if`( ! missing(treatment), treatment, NULL),
            `if`( ! missing(followupTime), followupTime, NULL),
            `if`( ! missing(outcomeCovs), outcomeCovs, NULL),
            `if`( ! missing(propensityCovs), propensityCovs, NULL),
            `if`( ! missing(censorCovs), censorCovs, NULL))


    options <- drSurvivalOptions$new(
        time = time,
        event = event,
        treatment = treatment,
        followupTime = followupTime,
        outcomeCovs = outcomeCovs,
        propensityCovs = propensityCovs,
        censorCovs = censorCovs,
        horizon = horizon,
        psMethod = psMethod,
        censorMethod = censorMethod,
        minPS = minPS,
        maxPS = maxPS,
        minCensorSurvival = minCensorSurvival,
        bootstrapSamples = bootstrapSamples,
        seed = seed,
        showBootstrapPlot = showBootstrapPlot,
        showSyntax = showSyntax)

    analysis <- drSurvivalClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

