
# This file is automatically generated, you probably don't want to edit this

landmarkTrialOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "landmarkTrialOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            eligibility = NULL,
            treatmentA = NULL,
            treatmentB = NULL,
            outcome = NULL,
            failureEvent1 = NULL,
            failureEvent2 = NULL,
            competingEvent = NULL,
            cluster = NULL,
            indexTime = NULL,
            treatmentATime = NULL,
            treatmentBTime = NULL,
            failureTime1 = NULL,
            failureTime2 = NULL,
            dischargeTime = NULL,
            competingTime = NULL,
            covariates = NULL,
            absenceVars = NULL,
            eligibilityPositive = "",
            treatmentAPositive = "",
            treatmentBPositive = "",
            outcomePositive = "",
            outcomeSource = "recorded",
            competingHandling = "noFailure",
            timeMode = "elapsed",
            timeUnit = "hours",
            window1 = 24,
            runSecondWindow = TRUE,
            window2 = 48,
            unknownTreatment = "exclude",
            unknownEvent = "exclude",
            runBothStrata = TRUE,
            primaryStratum = "present",
            primaryWindow = "first",
            missingMethod = "fail",
            imputations = 20,
            outcomeMethod = "auto",
            propensityMethod = "auto",
            minPS = 0.01,
            maxPS = 0.99,
            bootstrapSamples = 0,
            randomSeed = 24680,
            confidenceLevel = 95,
            effectMeasure = "riskDifference",
            showFlowPlot = TRUE,
            showBalancePlot = TRUE,
            showEffectPlot = TRUE,
            showSyntax = TRUE, ...) {

            super$initialize(
                package="trialemulationj",
                name="landmarkTrial",
                requiresData=TRUE,
                ...)

            private$..eligibility <- jmvcore::OptionVariable$new(
                "eligibility",
                eligibility,
                default=NULL)
            private$..treatmentA <- jmvcore::OptionVariable$new(
                "treatmentA",
                treatmentA)
            private$..treatmentB <- jmvcore::OptionVariable$new(
                "treatmentB",
                treatmentB)
            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome,
                default=NULL)
            private$..failureEvent1 <- jmvcore::OptionVariable$new(
                "failureEvent1",
                failureEvent1,
                default=NULL)
            private$..failureEvent2 <- jmvcore::OptionVariable$new(
                "failureEvent2",
                failureEvent2,
                default=NULL)
            private$..competingEvent <- jmvcore::OptionVariable$new(
                "competingEvent",
                competingEvent,
                default=NULL)
            private$..cluster <- jmvcore::OptionVariable$new(
                "cluster",
                cluster,
                default=NULL)
            private$..indexTime <- jmvcore::OptionVariable$new(
                "indexTime",
                indexTime,
                default=NULL)
            private$..treatmentATime <- jmvcore::OptionVariable$new(
                "treatmentATime",
                treatmentATime,
                default=NULL)
            private$..treatmentBTime <- jmvcore::OptionVariable$new(
                "treatmentBTime",
                treatmentBTime,
                default=NULL)
            private$..failureTime1 <- jmvcore::OptionVariable$new(
                "failureTime1",
                failureTime1,
                default=NULL)
            private$..failureTime2 <- jmvcore::OptionVariable$new(
                "failureTime2",
                failureTime2,
                default=NULL)
            private$..dischargeTime <- jmvcore::OptionVariable$new(
                "dischargeTime",
                dischargeTime,
                default=NULL)
            private$..competingTime <- jmvcore::OptionVariable$new(
                "competingTime",
                competingTime,
                default=NULL)
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                default=NULL)
            private$..absenceVars <- jmvcore::OptionVariables$new(
                "absenceVars",
                absenceVars,
                default=NULL)
            private$..eligibilityPositive <- jmvcore::OptionString$new(
                "eligibilityPositive",
                eligibilityPositive,
                default="")
            private$..treatmentAPositive <- jmvcore::OptionString$new(
                "treatmentAPositive",
                treatmentAPositive,
                default="")
            private$..treatmentBPositive <- jmvcore::OptionString$new(
                "treatmentBPositive",
                treatmentBPositive,
                default="")
            private$..outcomePositive <- jmvcore::OptionString$new(
                "outcomePositive",
                outcomePositive,
                default="")
            private$..outcomeSource <- jmvcore::OptionList$new(
                "outcomeSource",
                outcomeSource,
                options=list(
                    "recorded",
                    "composite"),
                default="recorded")
            private$..competingHandling <- jmvcore::OptionList$new(
                "competingHandling",
                competingHandling,
                options=list(
                    "noFailure",
                    "composite",
                    "exclude"),
                default="noFailure")
            private$..timeMode <- jmvcore::OptionList$new(
                "timeMode",
                timeMode,
                options=list(
                    "elapsed",
                    "dateTime"),
                default="elapsed")
            private$..timeUnit <- jmvcore::OptionList$new(
                "timeUnit",
                timeUnit,
                options=list(
                    "hours",
                    "days"),
                default="hours")
            private$..window1 <- jmvcore::OptionNumber$new(
                "window1",
                window1,
                min=0.01,
                max=10000,
                default=24)
            private$..runSecondWindow <- jmvcore::OptionBool$new(
                "runSecondWindow",
                runSecondWindow,
                default=TRUE)
            private$..window2 <- jmvcore::OptionNumber$new(
                "window2",
                window2,
                min=0.01,
                max=10000,
                default=48)
            private$..unknownTreatment <- jmvcore::OptionList$new(
                "unknownTreatment",
                unknownTreatment,
                options=list(
                    "exclude",
                    "assumeRecorded"),
                default="exclude")
            private$..unknownEvent <- jmvcore::OptionList$new(
                "unknownEvent",
                unknownEvent,
                options=list(
                    "exclude",
                    "retain"),
                default="exclude")
            private$..runBothStrata <- jmvcore::OptionBool$new(
                "runBothStrata",
                runBothStrata,
                default=TRUE)
            private$..primaryStratum <- jmvcore::OptionList$new(
                "primaryStratum",
                primaryStratum,
                options=list(
                    "present",
                    "absent"),
                default="present")
            private$..primaryWindow <- jmvcore::OptionList$new(
                "primaryWindow",
                primaryWindow,
                options=list(
                    "first",
                    "second"),
                default="first")
            private$..missingMethod <- jmvcore::OptionList$new(
                "missingMethod",
                missingMethod,
                options=list(
                    "fail",
                    "completeCases",
                    "hotDeckMI"),
                default="fail")
            private$..imputations <- jmvcore::OptionInteger$new(
                "imputations",
                imputations,
                min=2,
                max=100,
                default=20)
            private$..outcomeMethod <- jmvcore::OptionList$new(
                "outcomeMethod",
                outcomeMethod,
                options=list(
                    "auto",
                    "maximumLikelihood",
                    "firth"),
                default="auto")
            private$..propensityMethod <- jmvcore::OptionList$new(
                "propensityMethod",
                propensityMethod,
                options=list(
                    "auto",
                    "maximumLikelihood",
                    "firth"),
                default="auto")
            private$..minPS <- jmvcore::OptionNumber$new(
                "minPS",
                minPS,
                min=0.0001,
                max=0.49,
                default=0.01)
            private$..maxPS <- jmvcore::OptionNumber$new(
                "maxPS",
                maxPS,
                min=0.51,
                max=0.9999,
                default=0.99)
            private$..bootstrapSamples <- jmvcore::OptionInteger$new(
                "bootstrapSamples",
                bootstrapSamples,
                min=0,
                max=10000,
                default=0)
            private$..randomSeed <- jmvcore::OptionInteger$new(
                "randomSeed",
                randomSeed,
                min=1,
                max=2147483646,
                default=24680)
            private$..confidenceLevel <- jmvcore::OptionNumber$new(
                "confidenceLevel",
                confidenceLevel,
                min=80,
                max=99.9,
                default=95)
            private$..effectMeasure <- jmvcore::OptionList$new(
                "effectMeasure",
                effectMeasure,
                options=list(
                    "riskDifference",
                    "riskRatio",
                    "oddsRatio"),
                default="riskDifference")
            private$..showFlowPlot <- jmvcore::OptionBool$new(
                "showFlowPlot",
                showFlowPlot,
                default=TRUE)
            private$..showBalancePlot <- jmvcore::OptionBool$new(
                "showBalancePlot",
                showBalancePlot,
                default=TRUE)
            private$..showEffectPlot <- jmvcore::OptionBool$new(
                "showEffectPlot",
                showEffectPlot,
                default=TRUE)
            private$..showSyntax <- jmvcore::OptionBool$new(
                "showSyntax",
                showSyntax,
                default=TRUE)

            self$.addOption(private$..eligibility)
            self$.addOption(private$..treatmentA)
            self$.addOption(private$..treatmentB)
            self$.addOption(private$..outcome)
            self$.addOption(private$..failureEvent1)
            self$.addOption(private$..failureEvent2)
            self$.addOption(private$..competingEvent)
            self$.addOption(private$..cluster)
            self$.addOption(private$..indexTime)
            self$.addOption(private$..treatmentATime)
            self$.addOption(private$..treatmentBTime)
            self$.addOption(private$..failureTime1)
            self$.addOption(private$..failureTime2)
            self$.addOption(private$..dischargeTime)
            self$.addOption(private$..competingTime)
            self$.addOption(private$..covariates)
            self$.addOption(private$..absenceVars)
            self$.addOption(private$..eligibilityPositive)
            self$.addOption(private$..treatmentAPositive)
            self$.addOption(private$..treatmentBPositive)
            self$.addOption(private$..outcomePositive)
            self$.addOption(private$..outcomeSource)
            self$.addOption(private$..competingHandling)
            self$.addOption(private$..timeMode)
            self$.addOption(private$..timeUnit)
            self$.addOption(private$..window1)
            self$.addOption(private$..runSecondWindow)
            self$.addOption(private$..window2)
            self$.addOption(private$..unknownTreatment)
            self$.addOption(private$..unknownEvent)
            self$.addOption(private$..runBothStrata)
            self$.addOption(private$..primaryStratum)
            self$.addOption(private$..primaryWindow)
            self$.addOption(private$..missingMethod)
            self$.addOption(private$..imputations)
            self$.addOption(private$..outcomeMethod)
            self$.addOption(private$..propensityMethod)
            self$.addOption(private$..minPS)
            self$.addOption(private$..maxPS)
            self$.addOption(private$..bootstrapSamples)
            self$.addOption(private$..randomSeed)
            self$.addOption(private$..confidenceLevel)
            self$.addOption(private$..effectMeasure)
            self$.addOption(private$..showFlowPlot)
            self$.addOption(private$..showBalancePlot)
            self$.addOption(private$..showEffectPlot)
            self$.addOption(private$..showSyntax)
        }),
    active = list(
        eligibility = function() private$..eligibility$value,
        treatmentA = function() private$..treatmentA$value,
        treatmentB = function() private$..treatmentB$value,
        outcome = function() private$..outcome$value,
        failureEvent1 = function() private$..failureEvent1$value,
        failureEvent2 = function() private$..failureEvent2$value,
        competingEvent = function() private$..competingEvent$value,
        cluster = function() private$..cluster$value,
        indexTime = function() private$..indexTime$value,
        treatmentATime = function() private$..treatmentATime$value,
        treatmentBTime = function() private$..treatmentBTime$value,
        failureTime1 = function() private$..failureTime1$value,
        failureTime2 = function() private$..failureTime2$value,
        dischargeTime = function() private$..dischargeTime$value,
        competingTime = function() private$..competingTime$value,
        covariates = function() private$..covariates$value,
        absenceVars = function() private$..absenceVars$value,
        eligibilityPositive = function() private$..eligibilityPositive$value,
        treatmentAPositive = function() private$..treatmentAPositive$value,
        treatmentBPositive = function() private$..treatmentBPositive$value,
        outcomePositive = function() private$..outcomePositive$value,
        outcomeSource = function() private$..outcomeSource$value,
        competingHandling = function() private$..competingHandling$value,
        timeMode = function() private$..timeMode$value,
        timeUnit = function() private$..timeUnit$value,
        window1 = function() private$..window1$value,
        runSecondWindow = function() private$..runSecondWindow$value,
        window2 = function() private$..window2$value,
        unknownTreatment = function() private$..unknownTreatment$value,
        unknownEvent = function() private$..unknownEvent$value,
        runBothStrata = function() private$..runBothStrata$value,
        primaryStratum = function() private$..primaryStratum$value,
        primaryWindow = function() private$..primaryWindow$value,
        missingMethod = function() private$..missingMethod$value,
        imputations = function() private$..imputations$value,
        outcomeMethod = function() private$..outcomeMethod$value,
        propensityMethod = function() private$..propensityMethod$value,
        minPS = function() private$..minPS$value,
        maxPS = function() private$..maxPS$value,
        bootstrapSamples = function() private$..bootstrapSamples$value,
        randomSeed = function() private$..randomSeed$value,
        confidenceLevel = function() private$..confidenceLevel$value,
        effectMeasure = function() private$..effectMeasure$value,
        showFlowPlot = function() private$..showFlowPlot$value,
        showBalancePlot = function() private$..showBalancePlot$value,
        showEffectPlot = function() private$..showEffectPlot$value,
        showSyntax = function() private$..showSyntax$value),
    private = list(
        ..eligibility = NA,
        ..treatmentA = NA,
        ..treatmentB = NA,
        ..outcome = NA,
        ..failureEvent1 = NA,
        ..failureEvent2 = NA,
        ..competingEvent = NA,
        ..cluster = NA,
        ..indexTime = NA,
        ..treatmentATime = NA,
        ..treatmentBTime = NA,
        ..failureTime1 = NA,
        ..failureTime2 = NA,
        ..dischargeTime = NA,
        ..competingTime = NA,
        ..covariates = NA,
        ..absenceVars = NA,
        ..eligibilityPositive = NA,
        ..treatmentAPositive = NA,
        ..treatmentBPositive = NA,
        ..outcomePositive = NA,
        ..outcomeSource = NA,
        ..competingHandling = NA,
        ..timeMode = NA,
        ..timeUnit = NA,
        ..window1 = NA,
        ..runSecondWindow = NA,
        ..window2 = NA,
        ..unknownTreatment = NA,
        ..unknownEvent = NA,
        ..runBothStrata = NA,
        ..primaryStratum = NA,
        ..primaryWindow = NA,
        ..missingMethod = NA,
        ..imputations = NA,
        ..outcomeMethod = NA,
        ..propensityMethod = NA,
        ..minPS = NA,
        ..maxPS = NA,
        ..bootstrapSamples = NA,
        ..randomSeed = NA,
        ..confidenceLevel = NA,
        ..effectMeasure = NA,
        ..showFlowPlot = NA,
        ..showBalancePlot = NA,
        ..showEffectPlot = NA,
        ..showSyntax = NA)
)

landmarkTrialResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "landmarkTrialResults",
    inherit = jmvcore::Group,
    active = list(
        summary = function() private$.items[["summary"]],
        flow = function() private$.items[["flow"]],
        timeline = function() private$.items[["timeline"]],
        strategies = function() private$.items[["strategies"]],
        effects = function() private$.items[["effects"]],
        balance = function() private$.items[["balance"]],
        flowPlot = function() private$.items[["flowPlot"]],
        balancePlot = function() private$.items[["balancePlot"]],
        effectPlot = function() private$.items[["effectPlot"]],
        notes = function() private$.items[["notes"]],
        syntax = function() private$.items[["syntax"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Landmark Target-Trial Analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="Analysis Summary",
                rows=12,
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="flow",
                title="Landmark Cohort Flow",
                columns=list(
                    list(
                        `name`="window", 
                        `title`="Window", 
                        `type`="text"),
                    list(
                        `name`="step", 
                        `title`="Cohort step", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="Remaining N", 
                        `type`="integer"),
                    list(
                        `name`="excluded", 
                        `title`="Excluded at step", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="timeline",
                title="Timeline and Classification Audit",
                columns=list(
                    list(
                        `name`="variable", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="issue", 
                        `title`="Issue", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="action", 
                        `title`="Analysis action", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="strategies",
                title="Four-Strategy Classification",
                columns=list(
                    list(
                        `name`="window", 
                        `title`="Window", 
                        `type`="text"),
                    list(
                        `name`="treatmentA", 
                        `title`="Treatment A", 
                        `type`="text"),
                    list(
                        `name`="treatmentB", 
                        `title`="Treatment B", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="failures", 
                        `title`="Failures", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effects",
                title="Landmark Causal Effects",
                columns=list(
                    list(
                        `name`="window", 
                        `title`="Window", 
                        `type`="text"),
                    list(
                        `name`="stratum", 
                        `title`="Stratum", 
                        `type`="text"),
                    list(
                        `name`="method", 
                        `title`="Method", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="treated", 
                        `title`="Exposed N", 
                        `type`="integer"),
                    list(
                        `name`="failures", 
                        `title`="Failures", 
                        `type`="integer"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower CI", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper CI", 
                        `type`="number"),
                    list(
                        `name`="outcomeModel", 
                        `title`="Outcome model", 
                        `type`="text"),
                    list(
                        `name`="bootstrapSuccess", 
                        `title`="Successful bootstraps", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="balance",
                title="Primary-Specification Covariate Balance",
                columns=list(
                    list(
                        `name`="covariate", 
                        `title`="Covariate / level", 
                        `type`="text"),
                    list(
                        `name`="unweighted", 
                        `title`="Unweighted SMD", 
                        `type`="number"),
                    list(
                        `name`="weighted", 
                        `title`="IPTW-weighted SMD", 
                        `type`="number"),
                    list(
                        `name`="acceptable", 
                        `title`="|SMD| < 0.10", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="flowPlot",
                title="Landmark Cohort Retention",
                visible="(showFlowPlot)",
                width=720,
                height=420,
                renderFun=".flowPlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="balancePlot",
                title="Covariate Balance Before and After Weighting",
                visible="(showBalancePlot)",
                width=760,
                height=500,
                renderFun=".balancePlot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="effectPlot",
                title="Landmark Effect Estimates",
                visible="(showEffectPlot)",
                width=820,
                height=500,
                renderFun=".effectPlot"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="notes",
                title="Interpretation and Diagnostics"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="syntax",
                title="Reproducible Specification",
                visible="(showSyntax)"))}))

landmarkTrialBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "landmarkTrialBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "trialemulationj",
                name = "landmarkTrial",
                version = c(1,1,0),
                options = options,
                results = landmarkTrialResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Landmark Target-Trial Analysis
#'
#' Constructs aligned landmark cohorts for two treatment-decision windows,
#' classifies two binary treatment components into four strategies, and
#' estimates within-stratum AIPW and IPTW effects with timing audits,
#' clustered inference, separation handling, and publication-ready plots.
#' 
#' @param data .
#' @param eligibility .
#' @param treatmentA .
#' @param treatmentB .
#' @param outcome .
#' @param failureEvent1 .
#' @param failureEvent2 .
#' @param competingEvent .
#' @param cluster .
#' @param indexTime .
#' @param treatmentATime .
#' @param treatmentBTime .
#' @param failureTime1 .
#' @param failureTime2 .
#' @param dischargeTime .
#' @param competingTime .
#' @param covariates .
#' @param absenceVars .
#' @param eligibilityPositive .
#' @param treatmentAPositive .
#' @param treatmentBPositive .
#' @param outcomePositive .
#' @param outcomeSource .
#' @param competingHandling .
#' @param timeMode .
#' @param timeUnit .
#' @param window1 .
#' @param runSecondWindow .
#' @param window2 .
#' @param unknownTreatment .
#' @param unknownEvent .
#' @param runBothStrata .
#' @param primaryStratum .
#' @param primaryWindow .
#' @param missingMethod .
#' @param imputations .
#' @param outcomeMethod .
#' @param propensityMethod .
#' @param minPS .
#' @param maxPS .
#' @param bootstrapSamples .
#' @param randomSeed .
#' @param confidenceLevel .
#' @param effectMeasure .
#' @param showFlowPlot .
#' @param showBalancePlot .
#' @param showEffectPlot .
#' @param showSyntax .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$flow} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$timeline} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$strategies} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effects} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$balance} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$flowPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$balancePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$effectPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$syntax} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary$asDF}
#'
#' \code{as.data.frame(results$summary)}
#'
#' @export
landmarkTrial <- function(
    data,
    eligibility = NULL,
    treatmentA,
    treatmentB,
    outcome = NULL,
    failureEvent1 = NULL,
    failureEvent2 = NULL,
    competingEvent = NULL,
    cluster = NULL,
    indexTime = NULL,
    treatmentATime = NULL,
    treatmentBTime = NULL,
    failureTime1 = NULL,
    failureTime2 = NULL,
    dischargeTime = NULL,
    competingTime = NULL,
    covariates = NULL,
    absenceVars = NULL,
    eligibilityPositive = "",
    treatmentAPositive = "",
    treatmentBPositive = "",
    outcomePositive = "",
    outcomeSource = "recorded",
    competingHandling = "noFailure",
    timeMode = "elapsed",
    timeUnit = "hours",
    window1 = 24,
    runSecondWindow = TRUE,
    window2 = 48,
    unknownTreatment = "exclude",
    unknownEvent = "exclude",
    runBothStrata = TRUE,
    primaryStratum = "present",
    primaryWindow = "first",
    missingMethod = "fail",
    imputations = 20,
    outcomeMethod = "auto",
    propensityMethod = "auto",
    minPS = 0.01,
    maxPS = 0.99,
    bootstrapSamples = 0,
    randomSeed = 24680,
    confidenceLevel = 95,
    effectMeasure = "riskDifference",
    showFlowPlot = TRUE,
    showBalancePlot = TRUE,
    showEffectPlot = TRUE,
    showSyntax = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("landmarkTrial requires jmvcore to be installed (restart may be required)")

    if ( ! missing(eligibility)) eligibility <- jmvcore::resolveQuo(jmvcore::enquo(eligibility))
    if ( ! missing(treatmentA)) treatmentA <- jmvcore::resolveQuo(jmvcore::enquo(treatmentA))
    if ( ! missing(treatmentB)) treatmentB <- jmvcore::resolveQuo(jmvcore::enquo(treatmentB))
    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(failureEvent1)) failureEvent1 <- jmvcore::resolveQuo(jmvcore::enquo(failureEvent1))
    if ( ! missing(failureEvent2)) failureEvent2 <- jmvcore::resolveQuo(jmvcore::enquo(failureEvent2))
    if ( ! missing(competingEvent)) competingEvent <- jmvcore::resolveQuo(jmvcore::enquo(competingEvent))
    if ( ! missing(cluster)) cluster <- jmvcore::resolveQuo(jmvcore::enquo(cluster))
    if ( ! missing(indexTime)) indexTime <- jmvcore::resolveQuo(jmvcore::enquo(indexTime))
    if ( ! missing(treatmentATime)) treatmentATime <- jmvcore::resolveQuo(jmvcore::enquo(treatmentATime))
    if ( ! missing(treatmentBTime)) treatmentBTime <- jmvcore::resolveQuo(jmvcore::enquo(treatmentBTime))
    if ( ! missing(failureTime1)) failureTime1 <- jmvcore::resolveQuo(jmvcore::enquo(failureTime1))
    if ( ! missing(failureTime2)) failureTime2 <- jmvcore::resolveQuo(jmvcore::enquo(failureTime2))
    if ( ! missing(dischargeTime)) dischargeTime <- jmvcore::resolveQuo(jmvcore::enquo(dischargeTime))
    if ( ! missing(competingTime)) competingTime <- jmvcore::resolveQuo(jmvcore::enquo(competingTime))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if ( ! missing(absenceVars)) absenceVars <- jmvcore::resolveQuo(jmvcore::enquo(absenceVars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(eligibility), eligibility, NULL),
            `if`( ! missing(treatmentA), treatmentA, NULL),
            `if`( ! missing(treatmentB), treatmentB, NULL),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(failureEvent1), failureEvent1, NULL),
            `if`( ! missing(failureEvent2), failureEvent2, NULL),
            `if`( ! missing(competingEvent), competingEvent, NULL),
            `if`( ! missing(cluster), cluster, NULL),
            `if`( ! missing(indexTime), indexTime, NULL),
            `if`( ! missing(treatmentATime), treatmentATime, NULL),
            `if`( ! missing(treatmentBTime), treatmentBTime, NULL),
            `if`( ! missing(failureTime1), failureTime1, NULL),
            `if`( ! missing(failureTime2), failureTime2, NULL),
            `if`( ! missing(dischargeTime), dischargeTime, NULL),
            `if`( ! missing(competingTime), competingTime, NULL),
            `if`( ! missing(covariates), covariates, NULL),
            `if`( ! missing(absenceVars), absenceVars, NULL))


    options <- landmarkTrialOptions$new(
        eligibility = eligibility,
        treatmentA = treatmentA,
        treatmentB = treatmentB,
        outcome = outcome,
        failureEvent1 = failureEvent1,
        failureEvent2 = failureEvent2,
        competingEvent = competingEvent,
        cluster = cluster,
        indexTime = indexTime,
        treatmentATime = treatmentATime,
        treatmentBTime = treatmentBTime,
        failureTime1 = failureTime1,
        failureTime2 = failureTime2,
        dischargeTime = dischargeTime,
        competingTime = competingTime,
        covariates = covariates,
        absenceVars = absenceVars,
        eligibilityPositive = eligibilityPositive,
        treatmentAPositive = treatmentAPositive,
        treatmentBPositive = treatmentBPositive,
        outcomePositive = outcomePositive,
        outcomeSource = outcomeSource,
        competingHandling = competingHandling,
        timeMode = timeMode,
        timeUnit = timeUnit,
        window1 = window1,
        runSecondWindow = runSecondWindow,
        window2 = window2,
        unknownTreatment = unknownTreatment,
        unknownEvent = unknownEvent,
        runBothStrata = runBothStrata,
        primaryStratum = primaryStratum,
        primaryWindow = primaryWindow,
        missingMethod = missingMethod,
        imputations = imputations,
        outcomeMethod = outcomeMethod,
        propensityMethod = propensityMethod,
        minPS = minPS,
        maxPS = maxPS,
        bootstrapSamples = bootstrapSamples,
        randomSeed = randomSeed,
        confidenceLevel = confidenceLevel,
        effectMeasure = effectMeasure,
        showFlowPlot = showFlowPlot,
        showBalancePlot = showBalancePlot,
        showEffectPlot = showEffectPlot,
        showSyntax = showSyntax)

    analysis <- landmarkTrialClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

