
# This file is automatically generated, you probably don't want to edit this

protocolOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "protocolOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            studyTitle = "",
            population = "",
            eligibility = "",
            strategies = "",
            assignment = "Random assignment to a treatment strategy at time zero",
            timeZero = "",
            gracePeriod = "",
            followUp = "",
            outcome = "",
            competingEvents = "",
            causalContrast = "initiation",
            estimand = "ateDifference",
            confoundingPlan = "",
            analysisPlan = "",
            missingPlan = "",
            sensitivityPlan = "",
            acknowledgesAlignment = FALSE,
            acknowledgesFeasible = FALSE,
            acknowledgesBaseline = FALSE,
            acknowledgesPositivity = FALSE,
            showReport = TRUE, ...) {

            super$initialize(
                package="trialemulationj",
                name="protocol",
                requiresData=FALSE,
                ...)

            private$..studyTitle <- jmvcore::OptionString$new(
                "studyTitle",
                studyTitle,
                default="")
            private$..population <- jmvcore::OptionString$new(
                "population",
                population,
                default="")
            private$..eligibility <- jmvcore::OptionString$new(
                "eligibility",
                eligibility,
                default="")
            private$..strategies <- jmvcore::OptionString$new(
                "strategies",
                strategies,
                default="")
            private$..assignment <- jmvcore::OptionString$new(
                "assignment",
                assignment,
                default="Random assignment to a treatment strategy at time zero")
            private$..timeZero <- jmvcore::OptionString$new(
                "timeZero",
                timeZero,
                default="")
            private$..gracePeriod <- jmvcore::OptionString$new(
                "gracePeriod",
                gracePeriod,
                default="")
            private$..followUp <- jmvcore::OptionString$new(
                "followUp",
                followUp,
                default="")
            private$..outcome <- jmvcore::OptionString$new(
                "outcome",
                outcome,
                default="")
            private$..competingEvents <- jmvcore::OptionString$new(
                "competingEvents",
                competingEvents,
                default="")
            private$..causalContrast <- jmvcore::OptionList$new(
                "causalContrast",
                causalContrast,
                options=list(
                    "initiation",
                    "perProtocol",
                    "intentionToTreat"),
                default="initiation")
            private$..estimand <- jmvcore::OptionList$new(
                "estimand",
                estimand,
                options=list(
                    "ateDifference",
                    "ateRatio",
                    "survivalDifference",
                    "rmstDifference"),
                default="ateDifference")
            private$..confoundingPlan <- jmvcore::OptionString$new(
                "confoundingPlan",
                confoundingPlan,
                default="")
            private$..analysisPlan <- jmvcore::OptionString$new(
                "analysisPlan",
                analysisPlan,
                default="")
            private$..missingPlan <- jmvcore::OptionString$new(
                "missingPlan",
                missingPlan,
                default="")
            private$..sensitivityPlan <- jmvcore::OptionString$new(
                "sensitivityPlan",
                sensitivityPlan,
                default="")
            private$..acknowledgesAlignment <- jmvcore::OptionBool$new(
                "acknowledgesAlignment",
                acknowledgesAlignment,
                default=FALSE)
            private$..acknowledgesFeasible <- jmvcore::OptionBool$new(
                "acknowledgesFeasible",
                acknowledgesFeasible,
                default=FALSE)
            private$..acknowledgesBaseline <- jmvcore::OptionBool$new(
                "acknowledgesBaseline",
                acknowledgesBaseline,
                default=FALSE)
            private$..acknowledgesPositivity <- jmvcore::OptionBool$new(
                "acknowledgesPositivity",
                acknowledgesPositivity,
                default=FALSE)
            private$..showReport <- jmvcore::OptionBool$new(
                "showReport",
                showReport,
                default=TRUE)

            self$.addOption(private$..studyTitle)
            self$.addOption(private$..population)
            self$.addOption(private$..eligibility)
            self$.addOption(private$..strategies)
            self$.addOption(private$..assignment)
            self$.addOption(private$..timeZero)
            self$.addOption(private$..gracePeriod)
            self$.addOption(private$..followUp)
            self$.addOption(private$..outcome)
            self$.addOption(private$..competingEvents)
            self$.addOption(private$..causalContrast)
            self$.addOption(private$..estimand)
            self$.addOption(private$..confoundingPlan)
            self$.addOption(private$..analysisPlan)
            self$.addOption(private$..missingPlan)
            self$.addOption(private$..sensitivityPlan)
            self$.addOption(private$..acknowledgesAlignment)
            self$.addOption(private$..acknowledgesFeasible)
            self$.addOption(private$..acknowledgesBaseline)
            self$.addOption(private$..acknowledgesPositivity)
            self$.addOption(private$..showReport)
        }),
    active = list(
        studyTitle = function() private$..studyTitle$value,
        population = function() private$..population$value,
        eligibility = function() private$..eligibility$value,
        strategies = function() private$..strategies$value,
        assignment = function() private$..assignment$value,
        timeZero = function() private$..timeZero$value,
        gracePeriod = function() private$..gracePeriod$value,
        followUp = function() private$..followUp$value,
        outcome = function() private$..outcome$value,
        competingEvents = function() private$..competingEvents$value,
        causalContrast = function() private$..causalContrast$value,
        estimand = function() private$..estimand$value,
        confoundingPlan = function() private$..confoundingPlan$value,
        analysisPlan = function() private$..analysisPlan$value,
        missingPlan = function() private$..missingPlan$value,
        sensitivityPlan = function() private$..sensitivityPlan$value,
        acknowledgesAlignment = function() private$..acknowledgesAlignment$value,
        acknowledgesFeasible = function() private$..acknowledgesFeasible$value,
        acknowledgesBaseline = function() private$..acknowledgesBaseline$value,
        acknowledgesPositivity = function() private$..acknowledgesPositivity$value,
        showReport = function() private$..showReport$value),
    private = list(
        ..studyTitle = NA,
        ..population = NA,
        ..eligibility = NA,
        ..strategies = NA,
        ..assignment = NA,
        ..timeZero = NA,
        ..gracePeriod = NA,
        ..followUp = NA,
        ..outcome = NA,
        ..competingEvents = NA,
        ..causalContrast = NA,
        ..estimand = NA,
        ..confoundingPlan = NA,
        ..analysisPlan = NA,
        ..missingPlan = NA,
        ..sensitivityPlan = NA,
        ..acknowledgesAlignment = NA,
        ..acknowledgesFeasible = NA,
        ..acknowledgesBaseline = NA,
        ..acknowledgesPositivity = NA,
        ..showReport = NA)
)

protocolResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "protocolResults",
    inherit = jmvcore::Group,
    active = list(
        specification = function() private$.items[["specification"]],
        readiness = function() private$.items[["readiness"]],
        report = function() private$.items[["report"]],
        fingerprint = function() private$.items[["fingerprint"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Target-Trial Protocol Builder")
            self$add(jmvcore::Table$new(
                options=options,
                name="specification",
                title="Target-Trial Specification",
                columns=list(
                    list(
                        `name`="component", 
                        `title`="Component", 
                        `type`="text"),
                    list(
                        `name`="specification", 
                        `title`="Prespecified protocol", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="readiness",
                title="Design Readiness Checks",
                columns=list(
                    list(
                        `name`="check", 
                        `title`="Check", 
                        `type`="text"),
                    list(
                        `name`="status", 
                        `title`="Status", 
                        `type`="text"),
                    list(
                        `name`="action", 
                        `title`="Required action", 
                        `type`="text"))))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="report",
                title="Copy-Ready Protocol",
                visible="(showReport)"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="fingerprint",
                title="Reproducibility Record"))}))

protocolBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "protocolBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "trialemulationj",
                name = "protocol",
                version = c(1,1,0),
                options = options,
                results = protocolResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Target-Trial Protocol Builder
#'
#' Defines the target trial before analysis. Produces a structured protocol,
#' readiness checks, and a reproducible specification fingerprint aligned
#' with the core elements of target-trial and TARGET reporting guidance.
#' 
#' @param studyTitle .
#' @param population .
#' @param eligibility .
#' @param strategies .
#' @param assignment .
#' @param timeZero .
#' @param gracePeriod .
#' @param followUp .
#' @param outcome .
#' @param competingEvents .
#' @param causalContrast .
#' @param estimand .
#' @param confoundingPlan .
#' @param analysisPlan .
#' @param missingPlan .
#' @param sensitivityPlan .
#' @param acknowledgesAlignment .
#' @param acknowledgesFeasible .
#' @param acknowledgesBaseline .
#' @param acknowledgesPositivity .
#' @param showReport .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$specification} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$readiness} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$report} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$fingerprint} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$specification$asDF}
#'
#' \code{as.data.frame(results$specification)}
#'
#' @export
protocol <- function(
    studyTitle = "",
    population = "",
    eligibility = "",
    strategies = "",
    assignment = "Random assignment to a treatment strategy at time zero",
    timeZero = "",
    gracePeriod = "",
    followUp = "",
    outcome = "",
    competingEvents = "",
    causalContrast = "initiation",
    estimand = "ateDifference",
    confoundingPlan = "",
    analysisPlan = "",
    missingPlan = "",
    sensitivityPlan = "",
    acknowledgesAlignment = FALSE,
    acknowledgesFeasible = FALSE,
    acknowledgesBaseline = FALSE,
    acknowledgesPositivity = FALSE,
    showReport = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("protocol requires jmvcore to be installed (restart may be required)")


    options <- protocolOptions$new(
        studyTitle = studyTitle,
        population = population,
        eligibility = eligibility,
        strategies = strategies,
        assignment = assignment,
        timeZero = timeZero,
        gracePeriod = gracePeriod,
        followUp = followUp,
        outcome = outcome,
        competingEvents = competingEvents,
        causalContrast = causalContrast,
        estimand = estimand,
        confoundingPlan = confoundingPlan,
        analysisPlan = analysisPlan,
        missingPlan = missingPlan,
        sensitivityPlan = sensitivityPlan,
        acknowledgesAlignment = acknowledgesAlignment,
        acknowledgesFeasible = acknowledgesFeasible,
        acknowledgesBaseline = acknowledgesBaseline,
        acknowledgesPositivity = acknowledgesPositivity,
        showReport = showReport)

    analysis <- protocolClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

