
# This file is automatically generated, you probably don't want to edit this

targetTrialOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "targetTrialOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            id = NULL,
            period = NULL,
            treatment = NULL,
            outcome = NULL,
            eligible = NULL,
            estimand = "itt",
            outcomeCovs = NULL,
            useCensor = FALSE,
            censor = NULL,
            censorNumCovs = NULL,
            censorDenCovs = NULL,
            poolModels = "auto",
            switchNumCovs = NULL,
            switchDenCovs = NULL,
            followupModel = "quadratic",
            trialPeriodModel = "linear",
            targetPopulation = "all",
            targetTrialPeriod = 0,
            maxFollowUp = 10,
            confInt = TRUE,
            ciSamples = 500,
            predictionType = "cum_inc",
            truncateWeights = TRUE,
            truncatePercentile = 99,
            pControl = 1,
            chunkSize = 500,
            seed = 20240219,
            showSyntax = TRUE,
            showWeightPlot = TRUE, ...) {

            super$initialize(
                package="trialemulationj",
                name="targetTrial",
                requiresData=TRUE,
                ...)

            private$..id <- jmvcore::OptionVariable$new(
                "id",
                id)
            private$..period <- jmvcore::OptionVariable$new(
                "period",
                period,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..treatment <- jmvcore::OptionVariable$new(
                "treatment",
                treatment)
            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome)
            private$..eligible <- jmvcore::OptionVariable$new(
                "eligible",
                eligible)
            private$..estimand <- jmvcore::OptionList$new(
                "estimand",
                estimand,
                options=list(
                    "itt",
                    "pp"),
                default="itt")
            private$..outcomeCovs <- jmvcore::OptionVariables$new(
                "outcomeCovs",
                outcomeCovs,
                default=NULL)
            private$..useCensor <- jmvcore::OptionBool$new(
                "useCensor",
                useCensor,
                default=FALSE)
            private$..censor <- jmvcore::OptionVariable$new(
                "censor",
                censor,
                default=NULL)
            private$..censorNumCovs <- jmvcore::OptionVariables$new(
                "censorNumCovs",
                censorNumCovs,
                default=NULL)
            private$..censorDenCovs <- jmvcore::OptionVariables$new(
                "censorDenCovs",
                censorDenCovs,
                default=NULL)
            private$..poolModels <- jmvcore::OptionList$new(
                "poolModels",
                poolModels,
                options=list(
                    "auto",
                    "none",
                    "numerator",
                    "both"),
                default="auto")
            private$..switchNumCovs <- jmvcore::OptionVariables$new(
                "switchNumCovs",
                switchNumCovs,
                default=NULL)
            private$..switchDenCovs <- jmvcore::OptionVariables$new(
                "switchDenCovs",
                switchDenCovs,
                default=NULL)
            private$..followupModel <- jmvcore::OptionList$new(
                "followupModel",
                followupModel,
                options=list(
                    "linear",
                    "quadratic",
                    "spline3"),
                default="quadratic")
            private$..trialPeriodModel <- jmvcore::OptionList$new(
                "trialPeriodModel",
                trialPeriodModel,
                options=list(
                    "none",
                    "linear",
                    "quadratic"),
                default="linear")
            private$..targetPopulation <- jmvcore::OptionList$new(
                "targetPopulation",
                targetPopulation,
                options=list(
                    "all",
                    "earliest",
                    "latest",
                    "specific"),
                default="all")
            private$..targetTrialPeriod <- jmvcore::OptionInteger$new(
                "targetTrialPeriod",
                targetTrialPeriod,
                min=0,
                default=0)
            private$..maxFollowUp <- jmvcore::OptionInteger$new(
                "maxFollowUp",
                maxFollowUp,
                min=0,
                default=10)
            private$..confInt <- jmvcore::OptionBool$new(
                "confInt",
                confInt,
                default=TRUE)
            private$..ciSamples <- jmvcore::OptionInteger$new(
                "ciSamples",
                ciSamples,
                min=20,
                max=10000,
                default=500)
            private$..predictionType <- jmvcore::OptionList$new(
                "predictionType",
                predictionType,
                options=list(
                    "cum_inc",
                    "survival"),
                default="cum_inc")
            private$..truncateWeights <- jmvcore::OptionBool$new(
                "truncateWeights",
                truncateWeights,
                default=TRUE)
            private$..truncatePercentile <- jmvcore::OptionNumber$new(
                "truncatePercentile",
                truncatePercentile,
                min=90,
                max=100,
                default=99)
            private$..pControl <- jmvcore::OptionNumber$new(
                "pControl",
                pControl,
                min=0.01,
                max=1,
                default=1)
            private$..chunkSize <- jmvcore::OptionInteger$new(
                "chunkSize",
                chunkSize,
                min=10,
                max=1000000,
                default=500)
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                min=1,
                default=20240219)
            private$..showSyntax <- jmvcore::OptionBool$new(
                "showSyntax",
                showSyntax,
                default=TRUE)
            private$..showWeightPlot <- jmvcore::OptionBool$new(
                "showWeightPlot",
                showWeightPlot,
                default=TRUE)

            self$.addOption(private$..id)
            self$.addOption(private$..period)
            self$.addOption(private$..treatment)
            self$.addOption(private$..outcome)
            self$.addOption(private$..eligible)
            self$.addOption(private$..estimand)
            self$.addOption(private$..outcomeCovs)
            self$.addOption(private$..useCensor)
            self$.addOption(private$..censor)
            self$.addOption(private$..censorNumCovs)
            self$.addOption(private$..censorDenCovs)
            self$.addOption(private$..poolModels)
            self$.addOption(private$..switchNumCovs)
            self$.addOption(private$..switchDenCovs)
            self$.addOption(private$..followupModel)
            self$.addOption(private$..trialPeriodModel)
            self$.addOption(private$..targetPopulation)
            self$.addOption(private$..targetTrialPeriod)
            self$.addOption(private$..maxFollowUp)
            self$.addOption(private$..confInt)
            self$.addOption(private$..ciSamples)
            self$.addOption(private$..predictionType)
            self$.addOption(private$..truncateWeights)
            self$.addOption(private$..truncatePercentile)
            self$.addOption(private$..pControl)
            self$.addOption(private$..chunkSize)
            self$.addOption(private$..seed)
            self$.addOption(private$..showSyntax)
            self$.addOption(private$..showWeightPlot)
        }),
    active = list(
        id = function() private$..id$value,
        period = function() private$..period$value,
        treatment = function() private$..treatment$value,
        outcome = function() private$..outcome$value,
        eligible = function() private$..eligible$value,
        estimand = function() private$..estimand$value,
        outcomeCovs = function() private$..outcomeCovs$value,
        useCensor = function() private$..useCensor$value,
        censor = function() private$..censor$value,
        censorNumCovs = function() private$..censorNumCovs$value,
        censorDenCovs = function() private$..censorDenCovs$value,
        poolModels = function() private$..poolModels$value,
        switchNumCovs = function() private$..switchNumCovs$value,
        switchDenCovs = function() private$..switchDenCovs$value,
        followupModel = function() private$..followupModel$value,
        trialPeriodModel = function() private$..trialPeriodModel$value,
        targetPopulation = function() private$..targetPopulation$value,
        targetTrialPeriod = function() private$..targetTrialPeriod$value,
        maxFollowUp = function() private$..maxFollowUp$value,
        confInt = function() private$..confInt$value,
        ciSamples = function() private$..ciSamples$value,
        predictionType = function() private$..predictionType$value,
        truncateWeights = function() private$..truncateWeights$value,
        truncatePercentile = function() private$..truncatePercentile$value,
        pControl = function() private$..pControl$value,
        chunkSize = function() private$..chunkSize$value,
        seed = function() private$..seed$value,
        showSyntax = function() private$..showSyntax$value,
        showWeightPlot = function() private$..showWeightPlot$value),
    private = list(
        ..id = NA,
        ..period = NA,
        ..treatment = NA,
        ..outcome = NA,
        ..eligible = NA,
        ..estimand = NA,
        ..outcomeCovs = NA,
        ..useCensor = NA,
        ..censor = NA,
        ..censorNumCovs = NA,
        ..censorDenCovs = NA,
        ..poolModels = NA,
        ..switchNumCovs = NA,
        ..switchDenCovs = NA,
        ..followupModel = NA,
        ..trialPeriodModel = NA,
        ..targetPopulation = NA,
        ..targetTrialPeriod = NA,
        ..maxFollowUp = NA,
        ..confInt = NA,
        ..ciSamples = NA,
        ..predictionType = NA,
        ..truncateWeights = NA,
        ..truncatePercentile = NA,
        ..pControl = NA,
        ..chunkSize = NA,
        ..seed = NA,
        ..showSyntax = NA,
        ..showWeightPlot = NA)
)

targetTrialResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "targetTrialResults",
    inherit = jmvcore::Group,
    active = list(
        inputSummary = function() private$.items[["inputSummary"]],
        analysisSummary = function() private$.items[["analysisSummary"]],
        coefficients = function() private$.items[["coefficients"]],
        marginal = function() private$.items[["marginal"]],
        riskPlot = function() private$.items[["riskPlot"]],
        differencePlot = function() private$.items[["differencePlot"]],
        weightSummary = function() private$.items[["weightSummary"]],
        weightPlot = function() private$.items[["weightPlot"]],
        notes = function() private$.items[["notes"]],
        syntax = function() private$.items[["syntax"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Target Trial Emulation")
            self$add(jmvcore::Table$new(
                options=options,
                name="inputSummary",
                title="Input Data Summary",
                rows=7,
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="analysisSummary",
                title="Emulated Trial Summary",
                rows=8,
                columns=list(
                    list(
                        `name`="measure", 
                        `title`="Measure", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coefficients",
                title="Marginal Structural Model Coefficients",
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="Robust SE", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="lower", 
                        `title`="Lower 95%", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper 95%", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="marginal",
                title="Marginal Predictions and Treatment Contrast",
                columns=list(
                    list(
                        `name`="time", 
                        `title`="Follow-up", 
                        `type`="integer"),
                    list(
                        `name`="untreated", 
                        `title`="No treatment", 
                        `type`="number", 
                        `format`="zto,pc"),
                    list(
                        `name`="treated", 
                        `title`="Treatment", 
                        `type`="number", 
                        `format`="zto,pc"),
                    list(
                        `name`="difference", 
                        `title`="Difference", 
                        `type`="number", 
                        `format`="zto,pc"),
                    list(
                        `name`="lower", 
                        `title`="Lower 95%", 
                        `type`="number", 
                        `format`="zto,pc", 
                        `visible`="(confInt)"),
                    list(
                        `name`="upper", 
                        `title`="Upper 95%", 
                        `type`="number", 
                        `format`="zto,pc", 
                        `visible`="(confInt)"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="riskPlot",
                title="Marginal Curves",
                width=600,
                height=420,
                renderFun=".riskPlot",
                clearWith=list(
                    "predictionType",
                    "maxFollowUp",
                    "targetPopulation",
                    "targetTrialPeriod",
                    "confInt")))
            self$add(jmvcore::Image$new(
                options=options,
                name="differencePlot",
                title="Marginal Treatment Contrast",
                width=600,
                height=420,
                renderFun=".differencePlot",
                clearWith=list(
                    "predictionType",
                    "maxFollowUp",
                    "targetPopulation",
                    "targetTrialPeriod",
                    "confInt")))
            self$add(jmvcore::Table$new(
                options=options,
                name="weightSummary",
                title="Analysis Weight Diagnostics",
                columns=list(
                    list(
                        `name`="weight", 
                        `title`="Weight", 
                        `type`="text"),
                    list(
                        `name`="min", 
                        `title`="Min", 
                        `type`="number"),
                    list(
                        `name`="p1", 
                        `title`="P1", 
                        `type`="number"),
                    list(
                        `name`="p5", 
                        `title`="P5", 
                        `type`="number"),
                    list(
                        `name`="median", 
                        `title`="Median", 
                        `type`="number"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="p95", 
                        `title`="P95", 
                        `type`="number"),
                    list(
                        `name`="p99", 
                        `title`="P99", 
                        `type`="number"),
                    list(
                        `name`="max", 
                        `title`="Max", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="weightPlot",
                title="Final Analysis Weight Distribution",
                visible="(showWeightPlot)",
                width=600,
                height=380,
                renderFun=".weightPlot",
                clearWith=list(
                    "truncateWeights",
                    "truncatePercentile",
                    "pControl")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="notes",
                title="Interpretation and Diagnostics"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="syntax",
                title="Reproducible R Syntax",
                visible="(showSyntax)"))}))

targetTrialBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "targetTrialBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "trialemulationj",
                name = "targetTrial",
                version = c(1,1,1),
                options = options,
                results = targetTrialResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Target Trial Emulation
#'
#' Emulates a sequence of target trials from longitudinal person-period
#' observational data using the TrialEmulation R package. The analysis
#' estimates marginal intention-to-treat or per-protocol contrasts with a
#' pooled logistic marginal structural model and robust standard errors.
#' 
#' @param data the longitudinal person-period data as a data frame
#' @param id a string naming the individual identifier variable
#' @param period a string naming the non-negative integer visit or period
#'   variable
#' @param treatment a string naming the binary treatment status variable
#' @param outcome a string naming the binary outcome event variable
#' @param eligible a string naming the binary trial eligibility variable
#' @param estimand .
#' @param outcomeCovs baseline covariates used to adjust the marginal
#'   structural model
#' @param useCensor .
#' @param censor a string naming the binary censoring indicator
#' @param censorNumCovs .
#' @param censorDenCovs .
#' @param poolModels .
#' @param switchNumCovs .
#' @param switchDenCovs .
#' @param followupModel .
#' @param trialPeriodModel .
#' @param targetPopulation .
#' @param targetTrialPeriod .
#' @param maxFollowUp .
#' @param confInt .
#' @param ciSamples .
#' @param predictionType .
#' @param truncateWeights .
#' @param truncatePercentile .
#' @param pControl .
#' @param chunkSize .
#' @param seed .
#' @param showSyntax .
#' @param showWeightPlot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$inputSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$analysisSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$marginal} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$riskPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$differencePlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$weightSummary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$weightPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$notes} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$syntax} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$inputSummary$asDF}
#'
#' \code{as.data.frame(results$inputSummary)}
#'
#' @export
targetTrial <- function(
    data,
    id,
    period,
    treatment,
    outcome,
    eligible,
    estimand = "itt",
    outcomeCovs = NULL,
    useCensor = FALSE,
    censor = NULL,
    censorNumCovs = NULL,
    censorDenCovs = NULL,
    poolModels = "auto",
    switchNumCovs = NULL,
    switchDenCovs = NULL,
    followupModel = "quadratic",
    trialPeriodModel = "linear",
    targetPopulation = "all",
    targetTrialPeriod = 0,
    maxFollowUp = 10,
    confInt = TRUE,
    ciSamples = 500,
    predictionType = "cum_inc",
    truncateWeights = TRUE,
    truncatePercentile = 99,
    pControl = 1,
    chunkSize = 500,
    seed = 20240219,
    showSyntax = TRUE,
    showWeightPlot = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("targetTrial requires jmvcore to be installed (restart may be required)")

    if ( ! missing(id)) id <- jmvcore::resolveQuo(jmvcore::enquo(id))
    if ( ! missing(period)) period <- jmvcore::resolveQuo(jmvcore::enquo(period))
    if ( ! missing(treatment)) treatment <- jmvcore::resolveQuo(jmvcore::enquo(treatment))
    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(eligible)) eligible <- jmvcore::resolveQuo(jmvcore::enquo(eligible))
    if ( ! missing(outcomeCovs)) outcomeCovs <- jmvcore::resolveQuo(jmvcore::enquo(outcomeCovs))
    if ( ! missing(censor)) censor <- jmvcore::resolveQuo(jmvcore::enquo(censor))
    if ( ! missing(censorNumCovs)) censorNumCovs <- jmvcore::resolveQuo(jmvcore::enquo(censorNumCovs))
    if ( ! missing(censorDenCovs)) censorDenCovs <- jmvcore::resolveQuo(jmvcore::enquo(censorDenCovs))
    if ( ! missing(switchNumCovs)) switchNumCovs <- jmvcore::resolveQuo(jmvcore::enquo(switchNumCovs))
    if ( ! missing(switchDenCovs)) switchDenCovs <- jmvcore::resolveQuo(jmvcore::enquo(switchDenCovs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(id), id, NULL),
            `if`( ! missing(period), period, NULL),
            `if`( ! missing(treatment), treatment, NULL),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(eligible), eligible, NULL),
            `if`( ! missing(outcomeCovs), outcomeCovs, NULL),
            `if`( ! missing(censor), censor, NULL),
            `if`( ! missing(censorNumCovs), censorNumCovs, NULL),
            `if`( ! missing(censorDenCovs), censorDenCovs, NULL),
            `if`( ! missing(switchNumCovs), switchNumCovs, NULL),
            `if`( ! missing(switchDenCovs), switchDenCovs, NULL))


    options <- targetTrialOptions$new(
        id = id,
        period = period,
        treatment = treatment,
        outcome = outcome,
        eligible = eligible,
        estimand = estimand,
        outcomeCovs = outcomeCovs,
        useCensor = useCensor,
        censor = censor,
        censorNumCovs = censorNumCovs,
        censorDenCovs = censorDenCovs,
        poolModels = poolModels,
        switchNumCovs = switchNumCovs,
        switchDenCovs = switchDenCovs,
        followupModel = followupModel,
        trialPeriodModel = trialPeriodModel,
        targetPopulation = targetPopulation,
        targetTrialPeriod = targetTrialPeriod,
        maxFollowUp = maxFollowUp,
        confInt = confInt,
        ciSamples = ciSamples,
        predictionType = predictionType,
        truncateWeights = truncateWeights,
        truncatePercentile = truncatePercentile,
        pControl = pControl,
        chunkSize = chunkSize,
        seed = seed,
        showSyntax = showSyntax,
        showWeightPlot = showWeightPlot)

    analysis <- targetTrialClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

